### ISSUE TITLE
Question: Interpretation of output

### ISSUE THREAD

**Issue by expectopatronum** [NorskRegnesentral/shapr#180]
I'm currently playing around with the example from the README and I am not sure if everything is as clear as it could be. Could you explain what `none` means in the output or point the user to the description?
```r
print(explanation$dt)
#>      none     lstat         rm       dis      indus
#> 1: 22.446 5.2632030 -1.2526613 0.2920444  4.5528644
#> 2: 22.446 0.1671903 -0.7088405 0.9689007  0.3786871
#> 3: 22.446 5.9888016  5.5450861 0.5660136 -1.4304350
#> 4: 22.446 8.2142203  0.7507569 0.1893368  1.8298305
#> 5: 22.446 0.5059890  5.6875106 0.8432240  2.2471152
#> 6: 22.446 1.9929674 -3.6001959 0.8601984  3.1510531
```

Or you could call it 'average prediction' and also show the difference, like [here](https://christophm.github.io/interpretable-ml-book/shapley.html)?

**Comment by martinju** [comment]
Hi @expectopatronum 

Thanks for the question. Yes, we should make this clearer. The first column is the part of the prediction value which is not "due to" any of the features, hence "none". 
By design, the user can set this value. We prefer the mean response in the training data, while others use the mean prediction in the training data. 

While it would change the interpretation a bit, it is also possible to use other reference levels, like the mean prediction in a subset of the training or the data to be explained data. 

Other names like "reference level" could have been used, but I think "none" is fine when we provide short explanations of it in the help file of `shapr::explain`, the README and the vignette.

How does that sound?

**Comment by nikolase90** [comment]
@martinju I think it would be nice if we could add a section where we explain how you should interpret the `none`-column. It should be placed a the bottom of the section where we describe the output from `shapr::explain`. We do describe it for the features, but don't really say anything about the first column. Agree?

**Comment by nikolase90** [comment]
Below or above this chunk: 

```
#' If \code{dt[i, j + 1] > 0} it indicates that the j-th feature increased the prediction for
#' the i-th observation. Likewise, if \code{dt[i, j + 1] < 0} it indicates that the j-th feature
#' decreased the prediction for the i-th observation. The magnitude of the value is also important
#' to notice. E.g. if \code{dt[i, k + 1]} and \code{dt[i, j + 1]} are greater than \code{0},
#' where \code{j != k}, and \code{dt[i, k + 1]} > \code{dt[i, j + 1]} this indicates that feature
#' \code{j} and \code{k} both increased the value of the prediction, but that the effect of the k-th
#' feature was larger than the j-th feature.
```

Agree?

**Comment by martinju** [comment]
Working on it. I'll push a PR in a few minutes.

**Comment by nikolase90** [comment]
Ok, sweet.

**Comment by expectopatronum** [comment]
Is there a reason why you don't explicitly mention the name of the column `none`?

> The value in \code{dt[i, 1]} is the prediction value not assigned to any of the features

I actually had a hard time finding the description, because I couldn't find a mention in the README and the vignette. And I only found this paragraph by looking at the most recent commits :D

**Comment by nikolase90** [comment]
@expectopatronum Hehe, no it is not. Makes a lot more sense to actual use `none` instead. Will fix!
