### ISSUE TITLE
Reason for hard limit of max. 30 features?

### ISSUE THREAD

**Issue by mlds2020** [NorskRegnesentral/shapr#242]
Your code only supports datasets with <= 30 features -- what is the reason for that?

```
# Not supported for m > 30  
  if (m > 30) {  
    stop("Currently we are not supporting cases where the number of features is greater than 30.")  
  }
```

Does the approximation of n_combinations = 10 000 become unrepresentative with >30 features? Or does computational time explode exponential?
I am not aware of SHAP having limits to number of features.

**Comment by martinju** [comment]
Hi

Yes! The reason is exactly that since running the exact version with 30 features requires 2^30 > 10^9 feature combinations to run. While you could use the kernel shap approximation with fewer combinations, we believe the accuracy for running with e.g. 10^4 combinations will not be good enough to provide trustworthy results. If you got a very fast computer with lots of memory then you could maybe run a bit more than 10^4 samples. However, we have set this imaginary limit to 30 features to avoid typical users applying getting very bad results with our approach. 

I have an idea of a batch mode (see #244), similar to what I did manually here: https://github.com/NorskRegnesentral/shapr/commit/6d43468ad406fbaf7fa1ee70b3be111e7990e14a#diff-639dbfdc05cfa9df4cd9a3a1b798669638837cf999da4e7be64129e0d3996ed8

When this is implemented, one would hopefully be able to run bigger examples without severe memory issues, and I think we will remove the hard limit of 30 features. Unfortunately, this will not happen this year.

**Comment by martinju** [comment]
Hi

Yes! The reason is exactly that since running the exact version with 30 features requires 2^30 > 10^9 feature combinations to run. While you could use the kernel shap approximation with fewer combinations, we believe the accuracy for running with e.g. 10^4 combinations will not be good enough to provide trustworthy results. If you got a very fast computer with lots of memory then you could maybe run a bit more than 10^4 samples. However, we have set this imaginary limit to 30 features to avoid typical users applying getting very bad results with our approach. You are perfectly right that there is no theoretical hard limit here -- it is just a practical one.

As an alternative to the hard call to `stop`, we could consider making a warning + ask the user if he/she really wants to proceed. Would you be more satisfied with that approach since you could proceed if you really know what you are doing.

In any case, I have an idea of a batch mode (see #244), similar to what I did manually here: https://github.com/NorskRegnesentral/shapr/commit/6d43468ad406fbaf7fa1ee70b3be111e7990e14a#diff-639dbfdc05cfa9df4cd9a3a1b798669638837cf999da4e7be64129e0d3996ed8
When this is implemented, one would hopefully be able to run bigger examples without severe memory issues, and I will definitely remove the hard limit of 30 features completely. Unfortunately, this will not happen this year.

**Comment by salomonmroth** [comment]
Is there already an update planned on this topic or is there an expected timeframe? Thanks.
